# factorial

In [2]:
f = 1
x= int(input("Enter a number:"))
if x<0:
    print("factorial is not possible!")
elif x == 0:
    print("factorial is equal to 1.")
else:
    for i in range(1,x+1):
        f = f * i
    print("the factorial of  number ",x , "is:",f)




the factorial of  number  5 is: 120


# fibonacci

In [33]:
first = 0
second =1
print(first)
print(second)
for i in range(2,5):
    next = first+second
    first = second
    second = next
    print(next)

0
1
1
2
3


In [41]:
n = int(input("Enter the value of 'n': "))
a = 0
b = 1
sum = 0
count = 1
print("Fibonacci Series: ",end = " ")
while(count <= n):
  print(sum, end = " ")
  count += 1
  a = b
  b = sum
  sum = a + b

Fibonacci Series:  0 1 1 2 3 

#swappinng

In [4]:
a = int(input())
b = int(input())
c =a
a=b
b=c
print(a,b)

5 5


In [5]:
a=2
b=4
c=6
a,b,c= b,c,a
print(a,b,c)

4 6 2


In [6]:
a=5
b=2
a=a+b
b=a-b
a=a-b
print(a,b)

2 5


# reversal of a string

In [7]:
a="meghana mothukuru"
b = a.split(" ")
print(b)
c =  b[::-1]
print(c)
final = " ".join(c)
print(final)
len(a)
len(b)

['meghana', 'mothukuru']
['mothukuru', 'meghana']
mothukuru meghana


2

# prime number

In [8]:
x= int(input())
for i in range(2,x+1):
    if x%i ==0:
        print(x," not a prime number")
        break
else:
    print(x,"is a prime number")

5  not a prime number


# armstrong

In [9]:

num = int(input("enter a number:"))
sum=0
order = len(str(num))
a = num
while(num >0):
    digit = num% 10
    sum = sum+digit ** order
    num = num// 10
if sum == a:
    print(a,"is an armstring number")
else:
    print(a,"is not an armstrong  number")


5 is an armstring number


# call by value and reference

In [10]:
def tech(str):
    str = "meghana mothukuru"
    print("inside:",str)        # call by value
str = "iam"

tech(str)
print("ouside:",str)

inside: meghana mothukuru
ouside: iam


In [11]:
def tech(set):
    set.add(56)
    print("inside:",set)        # call by value
set1={12,34,50}
tech(set1)
print("ouside:",set1)


inside: {56, 34, 12, 50}
ouside: {56, 34, 12, 50}


# seocnd largest number

In [12]:

list=[1,5,3,6,7,90]
list.sort()
print(list)
print(list[-2])

[1, 3, 5, 6, 7, 90]
7


# palindrome

In [13]:
x= int(input())
reverse =0
num=x
while(x>0):
    digit = x%10
    reverse = reverse*10+digit
    x = x//10
if reverse == num:
    print(num,"is a palindrome number")
else:
    print(num,"is not a palinrome number")


ValueError: invalid literal for int() with base 10: '5\\'

# pattern

In [14]:
x= int(input())
for i in range(x):
    for j in range(i):
        print("*",end="")
    print("")


*
**
***
****
*****


In [15]:
x= int(input())
for i in range(x):
    for j in range(x):
        print("*",end="")
    print("")

*****
*****
*****
*****
*****


In [16]:
x= int(input())
for i in range(x):
    for j in range(i):
        print(j,end="")
    print("")


0
01
012
0123


# pascal traingle

In [18]:
# 1
#  11
# 121
#1331
#14641
rows=6
for i in range(rows):
    print(" "*(rows-i),end="")
    print(" ".join(map(str,str(11**i))))

TypeError: 'str' object is not callable

In [19]:
num = int(input("Enter the number:"))

for i in range(0, num):
    for j in range(1, i+1):
        print(" ", end="")
    for j in range(0, num):
        print("*", end="")
    print()

*****
 *****
  *****
   *****
    *****


# matrix multiplication

In [20]:
import numpy as np 
a = np.array([[1,4,5],[35,6,7],[34,7,3]])
b = np.array([[12,45,78],[34,67,52],[56,90,23]])
c = np.dot(a,b)
print(c)

[[ 428  763  401]
 [1016 2607 3203]
 [ 814 2269 3085]]


In [23]:
n=4
for i in range (n):
    print(''*i,'*'*n)

 ****
 ****
 ****
 ****


# gcd

In [30]:
num1 = 45
num2 = 60
gcd = 1
a=num1
b=num2
for i in range(1, min(num1,num2)):
    if num1 % i == 0 and num2 % i == 0:
        gcd = i
print("GCD of", num1, "and", num2, "is", gcd)
lcm = (a*b)//gcd
print("lcm is :",lcm)

GCD of 45 and 60 is 15
lcm is : 180


In [44]:

def calculate():
  print("+")
  print("-")
  print("*")
  print("/")
  operation = input("Select an operator:n")
  print("Enter two numbers")
  number_1 = int(input())
  number_2 = int(input())

  if operation == '+': # To add two numbers
    print(number_1 + number_2)

  elif operation == '-': # To subtract two numbers
    print(number_1 - number_2)

  elif operation == '*': # To multiply two numbers
    print(number_1 * number_2)

  elif operation == '/': # To divide two numbers
    print(number_1 / number_2)

  else:
    print('Invalid Input')
# Function Call
calculate()

+
-
*
/
Enter two numbers
63


In [56]:
choice = int(input("Enter your choice:n"))  # User's choice[1,2,3,4]
if (choice>=1 and choice<=4):
  print("Enter two numbers: ")
  num1 = int(input())
  num2 = int(input())
  print(num1,num2)
  if choice == 1: # To add two numbers
    res = num1 + num2
    print("Result = ", res)

  elif choice == 2: # To subtract two numbers
    res = num1 - num2
    print("Result = ", res)

  elif choice == 3: # To multiply two numbers
    res = num1 * num2
    print("Result = ", res)

  elif choice == 4: # To get quotient with decimal value
    res = num1 / num2
    print("Result = ", res)

  elif choice == 5:
    exit()
else:
  print("Wrong input..!!")

Wrong input..!!


In [61]:
rows = input("Enter the number of rows: ")
rows = int (rows)
for i in range (0, rows):
  for j in range(0, i + 1):
    print("*", end = ' ')
  print()

for i in range (rows, 0, -1):
   for j in range(0, i -1):
   
     print("*", end = ' ')
   print()

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 



In [87]:
#top half
rows = int(input("Enter the number of rows:" ))
k = 0
for i in range(1, rows + 1):
  # print spaces
    for j in range (1, (rows - i) + 1):
        print(end = " ")

    # let's print stars
    while k != (2 * i - 1):
        print("*", end = "")
        k = k + 1
    k = 0 # add a line break
    print()

#bottom half
k = 2
m = 1
for i in range(1, rows):
  # print spaces
    for j in range (1, k):
        print(end = " ")
        k = k + 1# print star
    while m <= (2 * (rows - i) - 1):
        print("*", end = "")
        m = m + 1
    m = 1#add a line break
    print() 

  *
 ***
*****
 ***
  *


In [93]:
#Python program to add all the array elements using the built-in function
lst = []
num = int(input("Enter the size of the array: "))
print("Enter array elements: ")
print(num)
sum=0
for n in range(num):
  numbers = int(input())
  lst.append(numbers)
for i in lst:
  sum = sum+i
print("list :",lst)
print("Sum:",sum )


Enter array elements: 
5
list : [3, 5, 6, 9, 5]
Sum: 28


In [7]:
n=int(input())
ar=[]
for i in range(n):
    ele = int(input())
    ar.append(ele)


def simpleArraySum(ar):
    # Write your code here

    return sum(ar)

simpleArraySum(ar)

23

In [11]:


a = list(map(int, input().rstrip().split()))

b = list(map(int, input().rstrip().split()))
print(a,b)

[] []


In [6]:
# cook your dish here
T = int(input())
while T > 0:
    x, y = map(int, input().split())
    
    if (x == 0 and y % 2 == 0):
        print("YES")
    elif (x == 0 and y % 2 != 0):
        print("NO")
    elif ((x + (2 * y)) % 2 == 0):
        print("YES")
    else:
        print("NO")
    T = T - 1

NO
NO
YES


In [15]:
    
def compareTriplets(a, b):
    # Write your code here
    n=len(a)
    a_s=0
    b_s=0
    for i in range(0,n):
        
        if a[i] > b[i]:
            a_s =a_s+1
            return a_s
        if a[i] < b[i]:
            b_s=b_s+1
            return b_s 
        if a[i]==b[i]:
            return "0"
print(result)





if __name__ == '__main__':
    

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a_s, b_s,)

    r = (' '.join(map(str, result)))

1


NameError: name 'a_s' is not defined